param([switch]$SkipExtension)

$ErrorActionPreference = 'Stop'
$projectDirectory = Split-Path -Parent $PSScriptRoot
Push-Location $projectDirectory
try {
    if (-not (Test-Path -LiteralPath '.venv/Scripts/python.exe')) {
        python -m venv .venv
        if ($LASTEXITCODE -ne 0) { throw 'Python environment creation failed' }
    }
    & '.venv/Scripts/python.exe' -m pip install -e '.[mcp]'
    if ($LASTEXITCODE -ne 0) { throw 'Python dependency installation failed' }
    $pythonCommandPath = (Resolve-Path -LiteralPath '.venv/Scripts/python.exe').Path.Replace('\', '/')
    $projectCommandDirectory = $projectDirectory.Replace('\', '/')
    $configurationDirectory = Join-Path $projectDirectory '.codex'
    New-Item -ItemType Directory -Force -Path $configurationDirectory | Out-Null
    $configurationPath = Join-Path $configurationDirectory 'config.toml'
    if (Test-Path -LiteralPath $configurationPath) {
        Write-Host 'Existing Codex configuration preserved. Add the MCP server using README instructions.'
    } else {
        # JSON double-quoted strings use compatible TOML basic-string escapes.
        # ConvertTo-Json also handles apostrophes and non-ASCII checkout paths.
        $pythonTomlString = ConvertTo-Json -InputObject $pythonCommandPath -Compress
        $directoryTomlString = ConvertTo-Json -InputObject $projectCommandDirectory -Compress
        $configurationContent = @"
# Project-local server. Generated by scripts/setup.ps1; start a new Codex session.
[mcp_servers.tiletrace]
command = $pythonTomlString
args = ["-m", "tiletrace", "mcp", "--session-dir", ".tiletrace"]
cwd = $directoryTomlString
"@
        # CreateNew preserves configuration created by another setup process.
        $configurationBytes = [System.Text.UTF8Encoding]::new($false).GetBytes($configurationContent)
        $configurationStream = $null
        try {
            $configurationStream = [System.IO.File]::Open($configurationPath, [System.IO.FileMode]::CreateNew)
        } catch [System.IO.IOException] {
            if (-not (Test-Path -LiteralPath $configurationPath)) { throw }
            Write-Host 'Existing Codex configuration preserved. Add the MCP server using README instructions.'
        }
        if ($null -ne $configurationStream) {
            try { $configurationStream.Write($configurationBytes, 0, $configurationBytes.Length) }
            finally { $configurationStream.Dispose() }
        }
    }
    if (-not $SkipExtension) {
        Push-Location (Join-Path $projectDirectory 'extension')
        try {
            npm.cmd ci
            if ($LASTEXITCODE -ne 0) { throw 'Extension dependency installation failed' }
            npm.cmd run package
            if ($LASTEXITCODE -ne 0) { throw 'Extension packaging failed' }
        } finally { Pop-Location }
    }
    Write-Host 'Setup complete. See README.md for extension installation and Codex connection.'
} finally { Pop-Location }
